// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILinearPremiumPriceOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILinearPremiumPriceOracle";
  readonly sourceName: "contracts/ethregistrar/ILinearPremiumPriceOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"expires","type":"uint256"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"timeUntilPremium","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ethregistrar/ILinearPremiumPriceOracle.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILinearPremiumPriceOracle"]: ILinearPremiumPriceOracle$Type;
    ["contracts/ethregistrar/ILinearPremiumPriceOracle.sol:ILinearPremiumPriceOracle"]: ILinearPremiumPriceOracle$Type;
  }
}