// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface AddressUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "AddressUtils";
  readonly sourceName: "contracts/utils/AddressUtils.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220677942b2c379d4dca90a9922a2320965467b619853b762f1a422087a9d70e4c564736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220677942b2c379d4dca90a9922a2320965467b619853b762f1a422087a9d70e4c564736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/AddressUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["AddressUtils"]: AddressUtils$Type;
    ["contracts/utils/AddressUtils.sol:AddressUtils"]: AddressUtils$Type;
  }
}