// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC721Receiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC721Receiver";
  readonly sourceName: "@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"operator","type":"address"},{"internalType":"address","name":"from","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"onERC721Received","outputs":[{"internalType":"bytes4","name":"","type":"bytes4"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "npm/@openzeppelin/contracts@4.9.3/token/ERC721/IERC721Receiver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC721Receiver"]: IERC721Receiver$Type;
    ["@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol:IERC721Receiver"]: IERC721Receiver$Type;
  }
}