// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ENSIP19$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ENSIP19";
  readonly sourceName: "contracts/utils/ENSIP19.sol";
  readonly abi: [{"inputs":[],"name":"EmptyAddress","type":"error"}];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122006a91fae50df0b982dbe46f79cb4f7519ff25efc5f29b2608289d0be4b9abb3864736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122006a91fae50df0b982dbe46f79cb4f7519ff25efc5f29b2608289d0be4b9abb3864736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/ENSIP19.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ENSIP19"]: ENSIP19$Type;
    ["contracts/utils/ENSIP19.sol:ENSIP19"]: ENSIP19$Type;
  }
}