// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DummyOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DummyOracle";
  readonly sourceName: "contracts/ethregistrar/DummyOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"int256","name":"_value","type":"int256"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"latestAnswer","outputs":[{"internalType":"int256","name":"","type":"int256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"int256","name":"_value","type":"int256"}],"name":"set","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600f57600080fd5b5060405161010b38038061010b833981016040819052602c916039565b603481600055565b506051565b600060208284031215604a57600080fd5b5051919050565b60ac8061005f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806350d25bcd146037578063e5c19b2d14604c575b600080fd5b60005460405190815260200160405180910390f35b605c6057366004605e565b600055565b005b600060208284031215606f57600080fd5b503591905056fea2646970667358221220f9a4843b321328063960ec48de1199d2b1a94c982c0a732bf8c4a5daa13aed7064736f6c634300081a0033";
  readonly deployedBytecode: "0x6080604052348015600f57600080fd5b506004361060325760003560e01c806350d25bcd146037578063e5c19b2d14604c575b600080fd5b60005460405190815260200160405180910390f35b605c6057366004605e565b600055565b005b600060208284031215606f57600080fd5b503591905056fea2646970667358221220f9a4843b321328063960ec48de1199d2b1a94c982c0a732bf8c4a5daa13aed7064736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ethregistrar/DummyOracle.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DummyOracle"]: DummyOracle$Type;
    ["contracts/ethregistrar/DummyOracle.sol:DummyOracle"]: DummyOracle$Type;
  }
}