// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IExtendedResolver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IExtendedResolver";
  readonly sourceName: "contracts/resolvers/profiles/IExtendedResolver.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"resolve","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/profiles/IExtendedResolver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IExtendedResolver"]: IExtendedResolver$Type;
    ["contracts/resolvers/profiles/IExtendedResolver.sol:IExtendedResolver"]: IExtendedResolver$Type;
  }
}