// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockOwnable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockOwnable";
  readonly sourceName: "contracts/test/mocks/MockOwnable.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_owner","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600f57600080fd5b50604051610137380380610137833981016040819052602c916050565b600080546001600160a01b0319166001600160a01b0392909216919091179055607e565b600060208284031215606157600080fd5b81516001600160a01b0381168114607757600080fd5b9392505050565b60ab8061008c6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638da5cb5b14602d575b600080fd5b600054604c9073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea2646970667358221220f3ba0f650cad579666567ffc1376cb950051f30596ab4a6b7954b8d53b30a24664736f6c634300081a0033";
  readonly deployedBytecode: "0x6080604052348015600f57600080fd5b506004361060285760003560e01c80638da5cb5b14602d575b600080fd5b600054604c9073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea2646970667358221220f3ba0f650cad579666567ffc1376cb950051f30596ab4a6b7954b8d53b30a24664736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/test/mocks/MockOwnable.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockOwnable"]: MockOwnable$Type;
    ["contracts/test/mocks/MockOwnable.sol:MockOwnable"]: MockOwnable$Type;
  }
}