// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DummyNameWrapper$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DummyNameWrapper";
  readonly sourceName: "contracts/resolvers/mocks/DummyNameWrapper.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"ownerOf","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600f57600080fd5b5060b480601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636352211e14602d575b600080fd5b603d60383660046066565b503290565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b600060208284031215607757600080fd5b503591905056fea26469706673582212201d2457b23ba6dde6675f00013b46969798a2772fa0c15050b4135ed5526a4bb664736f6c634300081a0033";
  readonly deployedBytecode: "0x6080604052348015600f57600080fd5b506004361060285760003560e01c80636352211e14602d575b600080fd5b603d60383660046066565b503290565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b600060208284031215607757600080fd5b503591905056fea26469706673582212201d2457b23ba6dde6675f00013b46969798a2772fa0c15050b4135ed5526a4bb664736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/mocks/DummyNameWrapper.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DummyNameWrapper"]: DummyNameWrapper$Type;
    ["contracts/resolvers/mocks/DummyNameWrapper.sol:DummyNameWrapper"]: DummyNameWrapper$Type;
  }
}