// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC7996$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC7996";
  readonly sourceName: "contracts/utils/IERC7996.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes4","name":"featureId","type":"bytes4"}],"name":"supportsFeature","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/IERC7996.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC7996"]: IERC7996$Type;
    ["contracts/utils/IERC7996.sol:IERC7996"]: IERC7996$Type;
  }
}