// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IMetadataService$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IMetadataService";
  readonly sourceName: "contracts/wrapper/IMetadataService.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"uri","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/wrapper/IMetadataService.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IMetadataService"]: IMetadataService$Type;
    ["contracts/wrapper/IMetadataService.sol:IMetadataService"]: IMetadataService$Type;
  }
}