// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ResolverFeatures$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ResolverFeatures";
  readonly sourceName: "contracts/resolvers/ResolverFeatures.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d1ea90d555a314048de0cd536b461f552ca0ecf4632d2e31b0dfa40ac907bdd864736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220d1ea90d555a314048de0cd536b461f552ca0ecf4632d2e31b0dfa40ac907bdd864736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/ResolverFeatures.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ResolverFeatures"]: ResolverFeatures$Type;
    ["contracts/resolvers/ResolverFeatures.sol:ResolverFeatures"]: ResolverFeatures$Type;
  }
}