// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IStandaloneReverseRegistrar$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IStandaloneReverseRegistrar";
  readonly sourceName: "contracts/reverseRegistrar/IStandaloneReverseRegistrar.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"addr","type":"address"},{"indexed":false,"internalType":"string","name":"name","type":"string"}],"name":"NameForAddrChanged","type":"event"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"nameForAddr","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/reverseRegistrar/IStandaloneReverseRegistrar.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IStandaloneReverseRegistrar"]: IStandaloneReverseRegistrar$Type;
    ["contracts/reverseRegistrar/IStandaloneReverseRegistrar.sol:IStandaloneReverseRegistrar"]: IStandaloneReverseRegistrar$Type;
  }
}