// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BytesUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BytesUtils";
  readonly sourceName: "contracts/utils/BytesUtils.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"offset","type":"uint256"},{"internalType":"uint256","name":"length","type":"uint256"}],"name":"OffsetOutOfBoundsError","type":"error"}];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208840f962f3b3b981ff5693ffe9263c1a631648ea3195c10a0669bc5468cc943064736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208840f962f3b3b981ff5693ffe9263c1a631648ea3195c10a0669bc5468cc943064736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/BytesUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BytesUtils"]: BytesUtils$Type;
    ["contracts/utils/BytesUtils.sol:BytesUtils"]: BytesUtils$Type;
  }
}