// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ModexpPrecompile$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ModexpPrecompile";
  readonly sourceName: "contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122062ad0b71556b0dad5762ea277820a31061416e2bdee9da9a2c5949b9eb94fde864736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122062ad0b71556b0dad5762ea277820a31061416e2bdee9da9a2c5949b9eb94fde864736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ModexpPrecompile"]: ModexpPrecompile$Type;
    ["contracts/dnssec-oracle/algorithms/ModexpPrecompile.sol:ModexpPrecompile"]: ModexpPrecompile$Type;
  }
}