// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SHA1$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SHA1";
  readonly sourceName: "contracts/dnssec-oracle/SHA1.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"bytes32","name":"x","type":"bytes32"}],"name":"Debug","type":"event"}];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f88afcdeae57e19c862121dbd862a1f4aea6d73a8632f13bc29bb16f80236c3e64736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f88afcdeae57e19c862121dbd862a1f4aea6d73a8632f13bc29bb16f80236c3e64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnssec-oracle/SHA1.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SHA1"]: SHA1$Type;
    ["contracts/dnssec-oracle/SHA1.sol:SHA1"]: SHA1$Type;
  }
}