// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface EIP3668$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "EIP3668";
  readonly sourceName: "contracts/ccipRead/EIP3668.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122074e4dabdc7b551cdc1ce186eb5967d582bae9221026d8144a3b12c3b1e2f757d64736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122074e4dabdc7b551cdc1ce186eb5967d582bae9221026d8144a3b12c3b1e2f757d64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ccipRead/EIP3668.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["EIP3668"]: EIP3668$Type;
    ["contracts/ccipRead/EIP3668.sol:EIP3668"]: EIP3668$Type;
  }
}