// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DNSClaimChecker$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DNSClaimChecker";
  readonly sourceName: "contracts/dnsregistrar/DNSClaimChecker.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122074c9f726d8ac745f6d2032732e2499de3f09f93eb8df28f0481cc84235f9465764736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122074c9f726d8ac745f6d2032732e2499de3f09f93eb8df28f0481cc84235f9465764736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnsregistrar/DNSClaimChecker.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DNSClaimChecker"]: DNSClaimChecker$Type;
    ["contracts/dnsregistrar/DNSClaimChecker.sol:DNSClaimChecker"]: DNSClaimChecker$Type;
  }
}