// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IDNSGateway$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IDNSGateway";
  readonly sourceName: "contracts/dnssec-oracle/IDNSGateway.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"uint16","name":"qtype","type":"uint16"}],"name":"resolve","outputs":[{"components":[{"internalType":"bytes","name":"rrset","type":"bytes"},{"internalType":"bytes","name":"sig","type":"bytes"}],"internalType":"struct DNSSEC.RRSetWithSignature[]","name":"","type":"tuple[]"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnssec-oracle/IDNSGateway.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IDNSGateway"]: IDNSGateway$Type;
    ["contracts/dnssec-oracle/IDNSGateway.sol:IDNSGateway"]: IDNSGateway$Type;
  }
}