// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUniversalSignatureValidator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUniversalSignatureValidator";
  readonly sourceName: "contracts/reverseRegistrar/SignatureUtils.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_signer","type":"address"},{"internalType":"bytes32","name":"_hash","type":"bytes32"},{"internalType":"bytes","name":"_signature","type":"bytes"}],"name":"isValidSig","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/reverseRegistrar/SignatureUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

export interface SignatureUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SignatureUtils";
  readonly sourceName: "contracts/reverseRegistrar/SignatureUtils.sol";
  readonly abi: [{"inputs":[],"name":"InvalidSignature","type":"error"},{"inputs":[],"name":"SignatureExpired","type":"error"},{"inputs":[],"name":"SignatureExpiryTooHigh","type":"error"},{"inputs":[],"name":"validator","outputs":[{"internalType":"contract IUniversalSignatureValidator","name":"","type":"IUniversalSignatureValidator"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x60b16037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80633a5381b5146038575b600080fd5b605273164af34faf9879394370c7f09064127c043a35e981565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea26469706673582212203ecbad0866b249a0d386769d8157ac22516198384ad95c0b1078855d8e14280764736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80633a5381b5146038575b600080fd5b605273164af34faf9879394370c7f09064127c043a35e981565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f3fea26469706673582212203ecbad0866b249a0d386769d8157ac22516198384ad95c0b1078855d8e14280764736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/reverseRegistrar/SignatureUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniversalSignatureValidator"]: IUniversalSignatureValidator$Type
    ["SignatureUtils"]: SignatureUtils$Type;
    ["contracts/reverseRegistrar/SignatureUtils.sol:IUniversalSignatureValidator"]: IUniversalSignatureValidator$Type
    ["contracts/reverseRegistrar/SignatureUtils.sol:SignatureUtils"]: SignatureUtils$Type;
  }
}