// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IHasAddressResolver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IHasAddressResolver";
  readonly sourceName: "contracts/resolvers/profiles/IHasAddressResolver.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"node","type":"bytes32"},{"internalType":"uint256","name":"coinType","type":"uint256"}],"name":"hasAddr","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/profiles/IHasAddressResolver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IHasAddressResolver"]: IHasAddressResolver$Type;
    ["contracts/resolvers/profiles/IHasAddressResolver.sol:IHasAddressResolver"]: IHasAddressResolver$Type;
  }
}