// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PublicSuffixList$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PublicSuffixList";
  readonly sourceName: "contracts/dnsregistrar/PublicSuffixList.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"isPublicSuffix","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnsregistrar/PublicSuffixList.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PublicSuffixList"]: PublicSuffixList$Type;
    ["contracts/dnsregistrar/PublicSuffixList.sol:PublicSuffixList"]: PublicSuffixList$Type;
  }
}