// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface HexUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "HexUtils";
  readonly sourceName: "contracts/utils/HexUtils.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e8355de215b5fc9d0fc2cd838ebb1cc1b15cd8262ba211a886072b496ff7253a64736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e8355de215b5fc9d0fc2cd838ebb1cc1b15cd8262ba211a886072b496ff7253a64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/HexUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["HexUtils"]: HexUtils$Type;
    ["contracts/utils/HexUtils.sol:HexUtils"]: HexUtils$Type;
  }
}