// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BytesUtils_LEGACY$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BytesUtils_LEGACY";
  readonly sourceName: "contracts/utils/BytesUtils_LEGACY.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220da374de2f0fd26d417da6a2070e20a5c520eded0d63006112c2311ac532ed6e264736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220da374de2f0fd26d417da6a2070e20a5c520eded0d63006112c2311ac532ed6e264736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/BytesUtils_LEGACY.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BytesUtils_LEGACY"]: BytesUtils_LEGACY$Type;
    ["contracts/utils/BytesUtils_LEGACY.sol:BytesUtils_LEGACY"]: BytesUtils_LEGACY$Type;
  }
}