// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RegistryUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RegistryUtils";
  readonly sourceName: "contracts/universalResolver/RegistryUtils.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b420a5f1f8de683aeec86ef2bd3100f3d431e9e52e5704257765f1ce41c1371b64736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b420a5f1f8de683aeec86ef2bd3100f3d431e9e52e5704257765f1ce41c1371b64736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/universalResolver/RegistryUtils.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RegistryUtils"]: RegistryUtils$Type;
    ["contracts/universalResolver/RegistryUtils.sol:RegistryUtils"]: RegistryUtils$Type;
  }
}