// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IL2ReverseRegistrar$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IL2ReverseRegistrar";
  readonly sourceName: "contracts/reverseRegistrar/IL2ReverseRegistrar.sol";
  readonly abi: [{"inputs":[{"internalType":"string","name":"name","type":"string"}],"name":"setName","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"},{"internalType":"string","name":"name","type":"string"}],"name":"setNameForAddr","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"},{"internalType":"uint256","name":"signatureExpiry","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"uint256[]","name":"coinTypes","type":"uint256[]"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"setNameForAddrWithSignature","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"contractAddr","type":"address"},{"internalType":"address","name":"owner","type":"address"},{"internalType":"uint256","name":"signatureExpiry","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"uint256[]","name":"coinTypes","type":"uint256[]"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"setNameForOwnableWithSignature","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/reverseRegistrar/IL2ReverseRegistrar.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IL2ReverseRegistrar"]: IL2ReverseRegistrar$Type;
    ["contracts/reverseRegistrar/IL2ReverseRegistrar.sol:IL2ReverseRegistrar"]: IL2ReverseRegistrar$Type;
  }
}