// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LibABI$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LibABI";
  readonly sourceName: "contracts/utils/LibABI.sol";
  readonly abi: [];
  readonly bytecode: "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202cde4ca7f0fe0d99ae1f8e408b09a46b16ea63d553ef4aadd143452e9d5f72d764736f6c634300081a0033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202cde4ca7f0fe0d99ae1f8e408b09a46b16ea63d553ef4aadd143452e9d5f72d764736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/LibABI.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LibABI"]: LibABI$Type;
    ["contracts/utils/LibABI.sol:LibABI"]: LibABI$Type;
  }
}