// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IGatewayProvider$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IGatewayProvider";
  readonly sourceName: "contracts/ccipRead/IGatewayProvider.sol";
  readonly abi: [{"inputs":[],"name":"gateways","outputs":[{"internalType":"string[]","name":"","type":"string[]"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ccipRead/IGatewayProvider.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IGatewayProvider"]: IGatewayProvider$Type;
    ["contracts/ccipRead/IGatewayProvider.sol:IGatewayProvider"]: IGatewayProvider$Type;
  }
}