// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBatchGateway$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBatchGateway";
  readonly sourceName: "contracts/ccipRead/IBatchGateway.sol";
  readonly abi: [{"inputs":[{"internalType":"uint16","name":"status","type":"uint16"},{"internalType":"string","name":"message","type":"string"}],"name":"HttpError","type":"error"},{"inputs":[{"components":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"string[]","name":"urls","type":"string[]"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct IBatchGateway.Request[]","name":"requests","type":"tuple[]"}],"name":"query","outputs":[{"internalType":"bool[]","name":"failures","type":"bool[]"},{"internalType":"bytes[]","name":"responses","type":"bytes[]"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ccipRead/IBatchGateway.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBatchGateway"]: IBatchGateway$Type;
    ["contracts/ccipRead/IBatchGateway.sol:IBatchGateway"]: IBatchGateway$Type;
  }
}