// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface INameWrapperUpgrade$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "INameWrapperUpgrade";
  readonly sourceName: "contracts/wrapper/INameWrapperUpgrade.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"address","name":"wrappedOwner","type":"address"},{"internalType":"uint32","name":"fuses","type":"uint32"},{"internalType":"uint64","name":"expiry","type":"uint64"},{"internalType":"address","name":"approved","type":"address"},{"internalType":"bytes","name":"extraData","type":"bytes"}],"name":"wrapFromUpgrade","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/wrapper/INameWrapperUpgrade.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["INameWrapperUpgrade"]: INameWrapperUpgrade$Type;
    ["contracts/wrapper/INameWrapperUpgrade.sol:INameWrapperUpgrade"]: INameWrapperUpgrade$Type;
  }
}