// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockReverseClaimerImplementer$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockReverseClaimerImplementer";
  readonly sourceName: "contracts/test/mocks/MockReverseClaimerImplementer.sol";
  readonly abi: [{"inputs":[{"internalType":"contract ENS","name":"ens","type":"address"},{"internalType":"address","name":"claimant","type":"address"}],"stateMutability":"nonpayable","type":"constructor"}];
  readonly bytecode: "0x608060405234801561001057600080fd5b5060405161021538038061021583398101604081905261002f91610151565b6040516302571be360e01b81527f91d1777781884d03a6757a803996e38de2a42967fb37eeaca72729271025a9e26004820152829082906000906001600160a01b038416906302571be390602401602060405180830381865afa15801561009a573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100be919061018b565b604051630f41a04d60e11b81526001600160a01b03848116600483015291925090821690631e83409a906024016020604051808303816000875af115801561010a573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061012e91906101af565b5050505050506101c8565b6001600160a01b038116811461014e57600080fd5b50565b6000806040838503121561016457600080fd5b825161016f81610139565b602084015190925061018081610139565b809150509250929050565b60006020828403121561019d57600080fd5b81516101a881610139565b9392505050565b6000602082840312156101c157600080fd5b5051919050565b603f806101d66000396000f3fe6080604052600080fdfea26469706673582212201b6700fb366c035947316be5b437cf38731d48b6f8b802b2952baa2aad4e6de964736f6c634300081a0033";
  readonly deployedBytecode: "0x6080604052600080fdfea26469706673582212201b6700fb366c035947316be5b437cf38731d48b6f8b802b2952baa2aad4e6de964736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/test/mocks/MockReverseClaimerImplementer.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockReverseClaimerImplementer"]: MockReverseClaimerImplementer$Type;
    ["contracts/test/mocks/MockReverseClaimerImplementer.sol:MockReverseClaimerImplementer"]: MockReverseClaimerImplementer$Type;
  }
}