// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUniversalResolver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUniversalResolver";
  readonly sourceName: "contracts/universalResolver/IUniversalResolver.sol";
  readonly abi: [{"inputs":[{"internalType":"uint16","name":"status","type":"uint16"},{"internalType":"string","name":"message","type":"string"}],"name":"HttpError","type":"error"},{"inputs":[{"internalType":"bytes","name":"errorData","type":"bytes"}],"name":"ResolverError","type":"error"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"address","name":"resolver","type":"address"}],"name":"ResolverNotContract","type":"error"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"ResolverNotFound","type":"error"},{"inputs":[{"internalType":"string","name":"primary","type":"string"},{"internalType":"bytes","name":"primaryAddress","type":"bytes"}],"name":"ReverseAddressMismatch","type":"error"},{"inputs":[{"internalType":"bytes4","name":"selector","type":"bytes4"}],"name":"UnsupportedResolverProfile","type":"error"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"findResolver","outputs":[{"internalType":"address","name":"resolver","type":"address"},{"internalType":"bytes32","name":"node","type":"bytes32"},{"internalType":"uint256","name":"resolverOffset","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"resolve","outputs":[{"internalType":"bytes","name":"result","type":"bytes"},{"internalType":"address","name":"resolver","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"lookupAddress","type":"bytes"},{"internalType":"uint256","name":"coinType","type":"uint256"}],"name":"reverse","outputs":[{"internalType":"string","name":"primary","type":"string"},{"internalType":"address","name":"resolver","type":"address"},{"internalType":"address","name":"reverseResolver","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/universalResolver/IUniversalResolver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniversalResolver"]: IUniversalResolver$Type;
    ["contracts/universalResolver/IUniversalResolver.sol:IUniversalResolver"]: IUniversalResolver$Type;
  }
}