// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Owned$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Owned";
  readonly sourceName: "contracts/dnssec-oracle/Owned.sol";
  readonly abi: [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"setOwner","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600f57600080fd5b50600080546001600160a01b03191633179055610177806100316000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806313af40351461003b5780638da5cb5b14610050575b600080fd5b61004e610049366004610104565b610099565b005b6000546100709073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1633146100bd57600080fd5b600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b60006020828403121561011657600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461013a57600080fd5b939250505056fea264697066735822122073dbe9a46a67b3f13b32be3f2dece623f1349a88bdd408848e1a22f66021e91464736f6c634300081a0033";
  readonly deployedBytecode: "0x608060405234801561001057600080fd5b50600436106100365760003560e01c806313af40351461003b5780638da5cb5b14610050575b600080fd5b61004e610049366004610104565b610099565b005b6000546100709073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1633146100bd57600080fd5b600080547fffffffffffffffffffffffff00000000000000000000000000000000000000001673ffffffffffffffffffffffffffffffffffffffff92909216919091179055565b60006020828403121561011657600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461013a57600080fd5b939250505056fea264697066735822122073dbe9a46a67b3f13b32be3f2dece623f1349a88bdd408848e1a22f66021e91464736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnssec-oracle/Owned.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Owned"]: Owned$Type;
    ["contracts/dnssec-oracle/Owned.sol:Owned"]: Owned$Type;
  }
}