// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ICompositeResolver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICompositeResolver";
  readonly sourceName: "contracts/resolvers/profiles/ICompositeResolver.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"getResolver","outputs":[{"internalType":"address","name":"resolver","type":"address"},{"internalType":"bool","name":"offchain","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"requiresOffchain","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"resolve","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/profiles/ICompositeResolver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ICompositeResolver"]: ICompositeResolver$Type;
    ["contracts/resolvers/profiles/ICompositeResolver.sol:ICompositeResolver"]: ICompositeResolver$Type;
  }
}