// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface NameCoder$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "NameCoder";
  readonly sourceName: "contracts/utils/NameCoder.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"dns","type":"bytes"}],"name":"DNSDecodingFailed","type":"error"},{"inputs":[{"internalType":"string","name":"ens","type":"string"}],"name":"DNSEncodingFailed","type":"error"},{"inputs":[],"name":"LabelIsEmpty","type":"error"},{"inputs":[{"internalType":"string","name":"label","type":"string"}],"name":"LabelIsTooLong","type":"error"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"},{"internalType":"bytes","name":"suffix","type":"bytes"}],"name":"NoSuffixMatch","type":"error"},{"inputs":[],"name":"ETH_NODE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x60a66037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063cc473be3146038575b600080fd5b605e7f8b2c096e21786c9afa7a1fedd1b69a27848cce61a49ec6363cd582b31efa669481565b60405190815260200160405180910390f3fea264697066735822122025b1449fd28911b6c20477965c2e9e961605b67d1f48bc3e2efb3d8daac2f46964736f6c634300081a0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063cc473be3146038575b600080fd5b605e7f8b2c096e21786c9afa7a1fedd1b69a27848cce61a49ec6363cd582b31efa669481565b60405190815260200160405180910390f3fea264697066735822122025b1449fd28911b6c20477965c2e9e961605b67d1f48bc3e2efb3d8daac2f46964736f6c634300081a0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/NameCoder.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["NameCoder"]: NameCoder$Type;
    ["contracts/utils/NameCoder.sol:NameCoder"]: NameCoder$Type;
  }
}