// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DNSSEC$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DNSSEC";
  readonly sourceName: "contracts/dnssec-oracle/DNSSEC.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint8","name":"id","type":"uint8"},{"indexed":false,"internalType":"address","name":"addr","type":"address"}],"name":"AlgorithmUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint8","name":"id","type":"uint8"},{"indexed":false,"internalType":"address","name":"addr","type":"address"}],"name":"DigestUpdated","type":"event"},{"inputs":[],"name":"anchors","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"},{"inputs":[{"components":[{"internalType":"bytes","name":"rrset","type":"bytes"},{"internalType":"bytes","name":"sig","type":"bytes"}],"internalType":"struct DNSSEC.RRSetWithSignature[]","name":"input","type":"tuple[]"},{"internalType":"uint256","name":"now","type":"uint256"}],"name":"verifyRRSet","outputs":[{"internalType":"bytes","name":"rrs","type":"bytes"},{"internalType":"uint32","name":"inception","type":"uint32"}],"stateMutability":"view","type":"function"},{"inputs":[{"components":[{"internalType":"bytes","name":"rrset","type":"bytes"},{"internalType":"bytes","name":"sig","type":"bytes"}],"internalType":"struct DNSSEC.RRSetWithSignature[]","name":"input","type":"tuple[]"}],"name":"verifyRRSet","outputs":[{"internalType":"bytes","name":"rrs","type":"bytes"},{"internalType":"uint32","name":"inception","type":"uint32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/dnssec-oracle/DNSSEC.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DNSSEC"]: DNSSEC$Type;
    ["contracts/dnssec-oracle/DNSSEC.sol:DNSSEC"]: DNSSEC$Type;
  }
}