// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBulkRenewal$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBulkRenewal";
  readonly sourceName: "contracts/ethregistrar/IBulkRenewal.sol";
  readonly abi: [{"inputs":[{"internalType":"string[]","name":"names","type":"string[]"},{"internalType":"uint256","name":"duration","type":"uint256"},{"internalType":"bytes32","name":"referrer","type":"bytes32"}],"name":"renewAll","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"string[]","name":"names","type":"string[]"},{"internalType":"uint256","name":"duration","type":"uint256"}],"name":"rentPrice","outputs":[{"internalType":"uint256","name":"total","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ethregistrar/IBulkRenewal.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBulkRenewal"]: IBulkRenewal$Type;
    ["contracts/ethregistrar/IBulkRenewal.sol:IBulkRenewal"]: IBulkRenewal$Type;
  }
}