// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IVerifiableResolver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IVerifiableResolver";
  readonly sourceName: "contracts/resolvers/profiles/IVerifiableResolver.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"bytes","name":"name","type":"bytes"},{"indexed":false,"internalType":"address","name":"verifier","type":"address"}],"name":"VerifierChanged","type":"event"},{"inputs":[{"internalType":"bytes","name":"name","type":"bytes"}],"name":"verifierMetadata","outputs":[{"internalType":"address","name":"verifier","type":"address"},{"internalType":"string[]","name":"gateways","type":"string[]"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/resolvers/profiles/IVerifiableResolver.sol";
  readonly buildInfoId: "solc-0_8_26-1202656001d821082cbbfd9e195672a31750ff6c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IVerifiableResolver"]: IVerifiableResolver$Type;
    ["contracts/resolvers/profiles/IVerifiableResolver.sol:IVerifiableResolver"]: IVerifiableResolver$Type;
  }
}